// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA5CymCYiYXNmlEYgTDyiodQgQi8xgBaU',
    appId: '1:863476607120:web:b9c56386c04dc4b2715015',
    messagingSenderId: '863476607120',
    projectId: 'fir-push-noti-d2e44',
    authDomain: 'fir-push-noti-d2e44.firebaseapp.com',
    storageBucket: 'fir-push-noti-d2e44.appspot.com',
    measurementId: 'G-H59L4KD1YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCghi3J8qLuqLo9D9NsO2MQhcn0t_tKVpc',
    appId: '1:863476607120:android:45897868f9f50f58715015',
    messagingSenderId: '863476607120',
    projectId: 'fir-push-noti-d2e44',
    storageBucket: 'fir-push-noti-d2e44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsD5dy68ub-NVd9-yBpsR6gvByf_1oNTI',
    appId: '1:863476607120:ios:2f1d1e5b07197fc2715015',
    messagingSenderId: '863476607120',
    projectId: 'fir-push-noti-d2e44',
    storageBucket: 'fir-push-noti-d2e44.appspot.com',
    iosBundleId: 'com.example.firebasePushNoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsD5dy68ub-NVd9-yBpsR6gvByf_1oNTI',
    appId: '1:863476607120:ios:2f1d1e5b07197fc2715015',
    messagingSenderId: '863476607120',
    projectId: 'fir-push-noti-d2e44',
    storageBucket: 'fir-push-noti-d2e44.appspot.com',
    iosBundleId: 'com.example.firebasePushNoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA5CymCYiYXNmlEYgTDyiodQgQi8xgBaU',
    appId: '1:863476607120:web:4004d1388e8c227d715015',
    messagingSenderId: '863476607120',
    projectId: 'fir-push-noti-d2e44',
    authDomain: 'fir-push-noti-d2e44.firebaseapp.com',
    storageBucket: 'fir-push-noti-d2e44.appspot.com',
    measurementId: 'G-5NJN0E3686',
  );
}
